### ISSUE TITLE
Changing email address leads to 500 Server error

### ISSUE THREAD

**Issue by Akhlys** [Csardelacal/PHPAuthServer#22]
Platform: Desktop
 Operating system: Windows
 Browser: Firefox
 URL: https://account.commishes.com/edit/email/
 
 What were you trying to do:
Changing email 

 What was supposed to happen:
Email changing 

 What happened:
Spitfire //Error page
500: Server error

Not much more to say

**Comment by Neop** [comment]
I can confirm this issue.

Platform: Desktop
Operating system: Linux (Debian)
Browser: Firefox and Chromium
URL: https://account.commishes.com/edit/email/
 
What were you trying to do:
Change email address
 
What was supposed to happen:
Email address being changed
 
What happened:
500: Class 'spitfire\validation\FilterValidationRule' not found
Class 'spitfire\validation\FilterValidationRule' not found
EditController->email(), in line 100
The complete stack trace: https://gist.github.com/Neop/fa05c789c587e3549fc3300375d9fba5

**Comment by Csardelacal** [comment]
Hey there you two, can you confirm whether the issue is still coming up for you? I pushed out a bugfix today and the issue should be resolved, if there's still any problems I'll have to investigate further.

**Comment by Akhlys** [comment]
Well.. It did not offer an error, but within now about 20 minutes, no confirmation mail appeared. Maybe it was sent to the old address, which doesn't exist any more, which was the reason I wanted to change the address. That's just a hunch tho

**Comment by Neop** [comment]
Same, didn't get one for either address. Tried the 'Resend activation mail' about 10-15 minutes ago, which didn't seem to help either (unless I just haven't waited long enough). Anyway, thanks for the fix so far!

**Comment by Akhlys** [comment]
Finally arrived, a day late. Possibly manually kicked off tho
