### ISSUE TITLE
What should I do if my account is accused of stealing someone else's work

### ISSUE THREAD

**Issue by yi-ww** [Csardelacal/PHPAuthServer#64]
I don't know where I should click to appeal, I don't quite understand English，I need guidance and assistance, what should I do

**Comment by yi-ww** [comment]
If I really steal someone else's work, then they should tell me whose work I stole, instead of being like this now

**Comment by yi-ww** [comment]
I really need a reply now, even if it's telling me to wait a moment, or even if it's telling me it's fast. I'm really in a hurry and I can't log in to reply to other people's messages

**Comment by Csardelacal** [comment]
Hey yi-ww, this is a software support space. It seems like you're not having issues with the software but the moderation team. Please refer to the account support.
